### PR TITLE
Add "Duplicate to" functionality

### PR DESCRIPTION
**Pull request by Syxton**

### CODE REVIEW

**Comment by cdsmith-umn** [comment]
@Syxton I'm looking at this and trying it out. I like the feature. One thing I noticed is that when you duplicate something, it actually moves the original copy to the "Duplicate to" destination and leaves the new copy in the section where the original was prior to the duplication. Was that intended? It seems counter-intuitive to me. (I had expected the new copy to be in the "Duplicate to" destination, with the original left in the original section.) How do you feel about my changing that behaviour?

**Comment by Syxton** [comment]
I actually hadn't noticed that..oops.  Absolutely needs to change.

**Comment by cdsmith-umn** [comment]
@Syxton No problem. I'll get it changed.

**Comment by cdsmith-umn** [comment]
This has been merged into Mass Actions and is available from the master branch now. Thank you! (Credit given in the README)

**Comment by Syxton** [comment]
I'm getting a 'Target section does not exist'  error when I tested this.

**Comment by cdsmith-umn** [comment]
I'll investigate

**Comment by Syxton** [comment]
I also noticed that the Move to box isn't being populated with sections.

**Comment by cdsmith-umn** [comment]
I have the first problem solved. Working on the Move to box

**Comment by Syxton** [comment]
module.js line 87 

        // add to move-to-section
        var section_option      = document.createElement('option');
        section_option.text     = section_text;
        section_option.value    = section_number;
        section_moveto.options[section_moveto.options.length] = section_option;

        // add to duplicate-to-section
        var section_option      = document.createElement('option');
        section_option.text     = section_text;
        section_option.value    = section_number;
        section_dupto.options[section_dupto.options.length] = section_option;

**Comment by Syxton** [comment]
not exactly sure why I couldn't reuse that variable....

**Comment by cdsmith-umn** [comment]
Yep. I just found the problem myself. I'll have it up on Github momentarily.

**Comment by cdsmith-umn** [comment]
The fix is up on Github now.

**Pull request closed without merging**
